### ISSUE TITLE
Ghosts Server Cleanup

### ISSUE THREAD

**Issue by pezhore** [cmu-sei/GHOSTS#126] opened 2022-09-09 13:22 UTC
First off, love this project. It is exactly what we need for an upcoming Red v Blue event. We will absolutely be pointing attendees to this project at the conclusion of the event as a great resource to develop various skillsets.

The only issue we're seeing is that the ghosts server is filling up the file system (200GB in less than 24 hours). To be fair, we have ~30 ghost npcs performing actions on a regular interval, but I'm not sure if something is missing for clean up?

I've traced the largest overlay2 volume to the Ghosts-API container - it looks like the `merged/tmp` and `diff/tmp` folders are each consuming ~100GB. 

Is there something I can do to periodically do cleanup for Ghosts API to allow longer-running efforts?

Here is our docker-compose file:

```yaml
# docker-compose up -d
# -f compose-api.yml (if you want a custom file)
# The Grafana volume mounts assume the directory structure matches the git repository

version: '3.2'
networks:
  ghosts-network:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name: ghosts-postgres
    environment:
      POSTGRES_DB: ghosts
      POSTGRES_USER: ghosts
      POSTGRES_PASSWORD: scotty@1
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./spectre_data:/tmp
    logging:
      options:
        max-size: '100m'
        max-file: '5'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ghosts']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ghosts-network
    restart: always

  ghosts-api:
    image: dustinupdyke/ghosts
    container_name: ghosts-api
    depends_on:
      - postgres
    ports:
      - '52388:5000'
    networks:
      - ghosts-network
    restart: always

  grafana:
    image: grafana/grafana
    container_name: ghosts-grafana
    user: root
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      - ghosts-network
    restart: always
    volumes:
      - ./g_data:/var/lib/grafana
      - ../../configuration/grafana/datasources:/etc/grafana/provisioning/datasources
      - ../../configuration/grafana/dashboards:/etc/grafana/provisioning/dashboards
```

**Comment by sei-dupdyke** [comment] 2022-09-09 15:23
Thanks for the kind words, and for checking out the project.

Sorry for the snag—I have not seen anything like this before. Investigating now...

**Comment by pezhore** [comment] 2022-09-10 12:40
Adding to this - I let the drive fill up again, it looks like the culprit is a ton of files `ASPNETCORE_[UUID].tmp` under `/merged/temp` and `/diff/tmp` in the ghosts-api container.

![image](https://user-images.githubusercontent.com/7430984/189483793-1aeae6f2-0761-46a3-8034-92461a1b9e18.png)

**Comment by avershave** [comment] 2022-09-12 13:56
[looks like there's a quick fix here. not sure if this is not needed but could be a quick, minor change.](https://stackoverflow.com/questions/62910894/asp-net-core-writes-request-body-to-windows-temp-folder)

**Comment by avershave** [comment] 2022-09-12 14:00
for nginx, any chance we can have a copy of the conf so we can try to troubleshoot the web header issue?

**Comment by sei-dupdyke** [comment] 2022-09-12 14:12
Clients construct a particular set of web headers that contain information about that client. This makes it a little difficult to use the API or a tool such as Postman to hit the api. What version of the API and clients are you using please?

**Comment by pezhore** [comment] 2022-09-12 18:01
> for nginx, any chance we can have a copy of the conf so we can try to troubleshoot the web header issue?

here you go:

```
server {

    listen 443 ssl;
    listen       [::]:443 ssl;

    server_name ghosts.cyber.range;


    index index.html index.htm;




    add_header X-Frame-Options DENY;
    ssl_certificate           /etc/ssl/certs/ghosts.my.domain-certificate.pem;
    ssl_certificate_key       /etc/ssl/private/ghosts.my.domain-private_key.pem;

    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers off;
    add_header Strict-Transport-Security "max-age=63072000" always;
    ssl_stapling on;
    ssl_stapling_verify on;
    location / {
      proxy_pass http://localhost:52388/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;

      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Nginx-Proxy true;

      proxy_redirect off;
    }

}
```

> Clients construct a particular set of web headers that contain information about that client. This makes it a little difficult to use the API or a tool such as Postman to hit the api. What version of the API and clients are you using please?

Ghosts server is running the latest docker image, the clients are running linux client v6.1.

**Comment by sei-dupdyke** [comment] 2022-09-15 14:49
Gah, I cannot recreate this issue. Is the proxy removing client headers by chance?

**Comment by pezhore** [comment] 2022-09-15 16:49
It's possible - for now, I'm just disabling the client updates portion and drives have stopped filling up. Unfortunately, our event starts next week  and I can't troubleshoot until afterwards.

I'll happily pick this back up so that we can figure out the resolution for future folks.

**Comment by sei-dupdyke** [comment] 2022-09-16 11:34
I found [a bug this morning](https://github.com/cmu-sei/GHOSTS/issues/129) that I wonder if this is related. Do you mind pulling the updated container and see if that fixes this issue please?

Another thing to check is that clients have `"IdEnabled": true,` in application.json config file.

**Comment by sei-dupdyke** [comment] 2022-10-31 14:55
I'm closing this because of non-reproducibility, we can reopen it if folks are still seeing it in the wild.

**Closed by sei-dupdyke** 2022-10-31 14:55 UTC
Labels: bug
