### ISSUE TITLE
Dynamically scale up and down NPC activity

### ISSUE THREAD

**Issue by drench79** [cmu-sei/GHOSTS#36] opened 2020-09-08 15:21 UTC
In an exercise it is useful to be able to scale up and scale down activity base on a number of different parameters, a big one being time based. It would also be useful if the NPC didn't restart the timeline each time it was updated and instead the timeline was dynamic so when the timeline was updated the process would dynamically and incrementally update. For example, if an NPC were able to scale up activity on a time scale starting at a certain time, say 0900 when they get into the office until 1200 when they take lunch break where the activity would subsequently drop off and then scale back up at 1300 when they arrive back from lunch and down again at 1600 when they leave the office.

**Comment by sei-dupdyke** [comment] 2020-10-09 12:53
@drench79 - I'm going to close this, because this is going to be part of another forthcoming GHOSTS module I am working on that will control and view the macro level of the range. 

I did add the ability for the core API and Clients to upload their current timelines, so that the C2 can know what each agent is currently doing (by default, the server doesn't know what the clients are doing out of the box, and that's by design so that if you want to run clients with no C2, that works fine). That will enable us to do things like "turn up the range activity by 10% right after lunch for 90 minutes, then 20% lower for an hour after that" == C2 retrieves all current timelines, adjusts them, and pushes them back down.

**Closed by sei-dupdyke** 2020-10-09 12:53 UTC
