### ISSUE TITLE
Grafana keeps stopping

### ISSUE THREAD

**Issue by configmanCooper** [cmu-sei/GHOSTS#262] opened 2024-01-12 01:14 UTC
I know there is documentation about chowning g_data but I have done that

I'm in the latest version of Ubuntu
The error I'm getting is as follows:

(HTTP code 500) server error - error while creating mount source path '/host_mnt/home/configuration/grafa/datasources': mkdir /host_mnt/home/configuration: permission denied

Thanks

**Comment by sei-dupdyke** [comment] 2024-01-12 19:44
dupe of #263

**Closed by sei-dupdyke** 2024-01-12 19:44 UTC
